version: '3.9'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
